[package]
name = "rust-ftw"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
http = "1.1"
lazy_static = "1.4"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
